services:
  evo_api:
    container_name: evo-api
    image: atendai/evolution-api:latest
    restart: always
    ports:
      - 8088:8080
    volumes:
      -  /home/glesioss/containers/evolution-api:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: typebot
      POSTGRES_DB: evolution_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - evolution-net
      - default

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6388:6379"
    networks:
      - evolution-net
      - default

volumes:
  evolution_api_aula:
  pg_data:

networks:
  evolution-net:
    driver: bridge