services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    networks:
      - weblocal
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/glesioss/containers/traefik/config/traefik.toml:/traefik.toml
      - /home/glesioss/containers/traefik/config/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=http"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/glesioss/containers/portainer/data:/data
    networks:
      - weblocal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.local`)"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.docker.network=weblocal"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  weblocal:
    external: true
